seed: 23

# Model parameters
model: LiquidAI/LFM2-VL-450M
structured_generation: true

# Dataset parameters
dataset: carrick113/cifar100
n_samples: 100
split: test

system_prompt: |
  You excel at identifying car makers from pictures.

user_prompt: |
  What car maker do you see in this picture?


image_column: image
label_column: maker